Add #removeError and #removeErrors to BufferedChangeset
adopted-ember-addons/validated-changeset pull request #189
Opened 2023-05-17 22:39 UTC by jkeen

I'm using `ember-changeset` with `ember-changeset-validations` with some validations where the presence requirement of one field is dependent on the value of another. If the dependent field ends up with an error, and then the field it depends on changes the error should really be cleared. But it didn't seem like there was a clean way to do that.

This path seems to be something that works in the newer `validated-changeset` 4.x-5.x experiment, but is not something available in BufferedChangeset. 

https://github.com/poteto/ember-changeset/issues/361
https://github.com/poteto/ember-changeset/issues/282

There were some workarounds in the above threads, like effectively "clearing" an error by `changeset.addError('email', null)`, but in my testing it still left the changeset with an `isValid = false` state.

This PR adds `removeError` and `removeErrors` to BufferedChangeset, mirroring the behavior in the newer ValidatedChangeset, and opening the door for an `ember-changeset` PR making this interface public.

2023-08-02 11:50 UTC, RuslanZavacky commented
@jkeen thank you for this PR! I hope it can be merged :) as it is very useful

2025-03-19 21:06 UTC, jkeen commented
@mansona Any chance this could be considered for merging? 

I just updated the linked PR on `ember-changeset`, but it depends on this one getting merged first. I still think this would be a good addition to the code base, and one I have been using in production via a private fork for almost two years now. Would be great to sync back up with the released version :)

2025-03-20 18:27 UTC, knownasilya requested changes
Looks mostly there, just a couple items

2025-03-20 18:27 UTC, knownasilya commented on src/index.ts
> +   * @method removeError
```suggestion
   * @method removeErrors
```

2025-03-20 18:27 UTC, knownasilya commented on test/index.test.ts
> +    });
Could you add multiple errors, and test that they are all gone?

2025-03-20 18:36 UTC, jkeen commented on test/index.test.ts
> +    });
@knownasilya Done

2025-03-20 18:39 UTC, merged